# Generated by Django 5.1.4 on 2024-12-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.CharField(max_length=100, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('massage', models.TextField(max_length=300, verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': ' تیکت ',
                'verbose_name_plural': ' تیکت ها ',
            },
        ),
    ]
