# Generated by Django 5.1.4 on 2024-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='massage',
            field=models.TextField(max_length=600, verbose_name='پیام'),
        ),
    ]
