# Generated by Django 5.1.4 on 2024-12-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' محصولات '},
        ),
    ]
