# Generated by Django 5.1.4 on 2024-12-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': ' دسته بندی ها '},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' محصول ', 'verbose_name_plural': ' محصولات '},
        ),
    ]
