# Generated by Django 5.1.4 on 2024-12-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttags',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.RemoveField(
            model_name='producttags',
            name='relatedProducts',
        ),
    ]
