# Generated by Django 5.1.4 on 2024-12-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_product_tag_producttags_product_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttags',
            name='product_tag',
        ),
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_tags', to='products.producttags'),
        ),
    ]
