# Generated by Django 5.1.4 on 2024-12-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_url',
        ),
    ]
