# Generated by Django 5.1.4 on 2024-12-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_slider',
            field=models.CharField(blank=True, choices=[('first', 'اسلایدر بالایی صفحه اول'), ('second', 'اسلایدر پایین صفحه اول'), ('none', 'در اسلایدر ها نباشد')], max_length=100, null=True, verbose_name='موقعیت در اسلاید'),
        ),
    ]
