# Generated by Django 5.1.4 on 2024-12-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_in_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='اسلاگ'),
        ),
    ]
