# Generated by Django 5.1.4 on 2025-01-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productsvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsvisit',
            old_name='Product',
            new_name='product',
        ),
    ]
