# Generated by Django 5.1.4 on 2025-01-08 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_rename_product_productsvisit_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsvisit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='products.product', verbose_name='محصول'),
        ),
    ]
