# Generated by Django 5.1.4 on 2024-12-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='لطفاً تصویر با کیفیت مناسب را بارگذاری کنید.', upload_to='banners/', verbose_name='تصویر بنر')),
                ('title', models.CharField(blank=True, help_text='عنوان بنر (اختیاری)', max_length=200, null=True, verbose_name='عنوان بنر')),
                ('description', models.TextField(blank=True, help_text='توضیحات بنر (اختیاری)', null=True, verbose_name='توضیحات بنر')),
                ('link', models.URLField(blank=True, help_text='لینک مقصد بنر (اختیاری)', null=True, verbose_name='لینک بنر')),
                ('position', models.CharField(choices=[('home', 'صفحه اصلی'), ('about', 'درباره ما'), ('contact', 'تماس با ما')], default='home', help_text='انتخاب موقعیت نمایش بنر', max_length=50, verbose_name='موقعیت بنر')),
                ('active', models.BooleanField(default=True, help_text='فعال کردن یا غیرفعال کردن بنر', verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['-created_at'],
            },
        ),
    ]
