# Generated by Django 5.1.4 on 2025-01-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aticel',
            options={'verbose_name': ' مقاله ', 'verbose_name_plural': ' مقالات'},
        ),
    ]
