# Generated by Django 5.1.4 on 2025-01-01 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0002_alter_aticel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aticel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Articels.articelcategories', verbose_name='دسته بندی مقاله'),
            preserve_default=False,
        ),
    ]
