# Generated by Django 5.1.4 on 2025-01-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0004_alter_articelcategories_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articelcategories',
            name='url',
            field=models.CharField(blank=True, help_text='عنوان درurl باید کارکاتر های انگلیسی باشد', max_length=100, null=True, verbose_name='عنوان در url'),
        ),
    ]
