# Generated by Django 5.1.4 on 2025-01-05 07:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0006_articelcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aticel',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='متن مقاله'),
        ),
    ]
