# Generated by Django 5.1.4 on 2024-12-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='دامنه سایت')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/image', verbose_name='لوگوی سایت')),
                ('about', models.TextField(help_text='این متن در فوتر(پاورقی)  سایت استفاده میشود', verbose_name='توضیحات سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
