# Generated by Django 5.1.4 on 2024-12-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='site/image', verbose_name='آیکون سایت'),
        ),
    ]
