# Generated by Django 5.1.4 on 2024-12-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_sitesetting_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkCategory', models.CharField(max_length=100, verbose_name='دسته بندی لینک  های فوتر')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک فوتر',
                'verbose_name_plural': 'دسته بندی های لینک های فوتر',
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about',
            field=models.TextField(verbose_name='توضیحات سایت'),
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='لینک')),
                ('link_title', models.CharField(max_length=50, verbose_name='عنوان لینک')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.linkcategory', verbose_name='دسته بندی لینک')),
            ],
            options={
                'verbose_name': 'لینک  فوتر',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
    ]
