# Generated by Django 5.1.4 on 2024-12-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_linkcategory_sitesetting_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name=' لینک رسانه')),
                ('icon', models.ImageField(upload_to='site/image', verbose_name='آیکون رسانه')),
            ],
            options={
                'verbose_name': 'رسانه ',
                'verbose_name_plural': 'رسانه ها',
            },
        ),
    ]
