# Generated by Django 5.1.4 on 2024-12-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
