# Generated by Django 5.1.4 on 2025-01-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=123, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_nember',
            field=models.CharField(default=123, max_length=11, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default=123, max_length=10, verbose_name='کد پستی'),
            preserve_default=False,
        ),
    ]
