# Generated by Django 5.1.4 on 2025-01-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_address_user_phone_nember_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='users/image', verbose_name='عکس پروفایل'),
        ),
    ]
